### ISSUE TITLE
numpy版本问题

### ISSUE THREAD

**Issue by leaozhun** [Jingkang50/OpenPVSG#18]
+ PARTITION=priority
+ JOB_NAME=psg
+ CONFIG=configs/mask2former_vps/mask2former_video_r50.py
+ WORK_DIR=checkpoints/mask2former_r50_vps
+ PORT=1111
+ GPUS_PER_NODE=1
+ CPUS_PER_TASK=1
+ PY_ARGS=
+ PYTHONPATH=/mnt/lustre/jkyang/CVPR23/openpvsg:/media/dell/data1/cw/algo/git/tvm/python:/media/dell/data1/cw/algo/git/tvm/python:
+ python -u tools/train.py configs/mask2former_vps/mask2former_video_r50.py --work-dir=checkpoints/mask2former_r50_vps --launcher=none
Traceback (most recent call last):
  File "tools/train.py", line 22, in <module>
    import models
  File "/media/dell/data1/PZ/VidSGG/PVSG/models/__init__.py", line 14, in <module>
    from .unitrack.test_mots_from_mask2former import eval_seq
  File "/media/dell/data1/PZ/VidSGG/PVSG/models/unitrack/test_mots_from_mask2former.py", line 25, in <module>
    from models.unitrack.mask import MaskAssociationTracker
  File "/media/dell/data1/PZ/VidSGG/PVSG/models/unitrack/mask.py", line 14, in <module>
    from models.unitrack.basetrack import *
  File "/media/dell/data1/PZ/VidSGG/PVSG/models/unitrack/basetrack.py", line 4, in <module>
    import models.unitrack.core.association.matching as matching
  File "/media/dell/data1/PZ/VidSGG/PVSG/models/unitrack/core/association/matching.py", line 8, in <module>
    from cython_bbox import bbox_overlaps as bbox_ious
  File "src/cython_bbox.pyx", line 12, in init cython_bbox
  File "/media/dell/data1/miniconda3/envs/openpvsg/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
具体报错如上，请问您在实验时遇到过这样的问题吗

**Comment by leaozhun** [comment]
这个问题可以更新cython_bbox来解决，可能您可以在readme文档里加以补充？
